# 1. Flow Control

## 1.1 Decision Making

Decision structures evaluate multiple expressions which produce `True` or `False` as outcome. You need to determine which action to take and which statements to execute if outcome is `True` or `False` otherwise.

Following is the general form of a typical decision making structure in programming.

![decision_making](./figure/decision_making.jpg)

### 1.1.1 `if`, `elif` & `else`

These three keywords are used for decision making.

- `if` statement, check whether the condition is `True` or not
- `elif` statement, if the previous conditions were not true, then try this condition
- `else` statement, if all preceeding conditions are `False`, then excecute following statements

The **framework** is shown below. Note that the `elif` and `else` clauses are optional. 

```python
if expression:
    statement(s)
elif expression:
    statement(s)
elif expression:
    statement(s)
...
else:
    statement(s)
```

In [4]:
x = -15

if x == 0:
    print(x, "is zero")
elif x > 0:
    print(x, "is positive")
elif x < 0:
    print(x, "is negative")
else:
    print(x, "is unlike anything I've ever seen...")

-15 is negative


The keyword `elif` is short for `else if`, and is useful to avoid excessive indentation.

This below one has the same meaning with the above example but with much more indentaions.

Thus, we **avoid this bad style** in python programming.

In [7]:
x = -15

# this style is tedious
if x == 0:
    print(x, "is zero")
else:
    if x > 0:
        print(x, "is positive")
    else:
        if x < 0:
            print(x, "is negative")
        else:
            print(x, "is unlike anything I've ever seen...")

-15 is negative


You can use any Python expression as the condition in an if or elif clause. When you use an expression this way, you are using it in a Boolean context.

**Keep it simple.**

The `if x:` is equal to the following three statements. And this is the clearest and most Pythonic form.

```python
if x:

```

Don't use:

```python
if x is True:
if x =  = True:
if bool(x):
```

### 1.1.2 Short Hand Formats

**One line `if` statement**.

If you have only one statement to execute, you can put it on the same line as the if statement.

In [10]:
a = 3; b = 2
if a > b: print("a is greater than b")

a is greater than b


**One line if else statement**

This technique is known as Ternary Operators, or Conditional Expressions.

If you have only one statement to execute, one for if, and one for else, you can put it all on the same line:

In [ ]:
r = 'larger' if a > b else 'smaller'
print(r)

You can also have multiple else statements on the same line:

In [13]:
a = 310
b = 330
print("A") if a > b else print("=") if a == b else print("B")

B


## 1.1.3 `and` & `or`

The `and` and `or` logical operators are used to combine conditional statements.

In [16]:
a = 200
b = 33
c = 500

if a > b and c > a:
    print("Both conditions are True")

if a > b or a > c:
    print("At least one of the conditions is True")

Both conditions are True
At least one of the conditions is True


## 1.2 Loops

A loop statement allows us to execute a statement or group of statements multiple times. 

The following diagram illustrates a loop statement.

![loop_architecture](./figure/loop_architecture.jpg)

### 1.2.1 `while` loop

With the `while` loop we can execute a set of statements as long as a condition is true.

Here's the syntax for the `while` statement:

```python
while expression:
    statement(s)
```

In [17]:
# Print i as long as i is less than 6:
i = 1
while i < 6:
    print(i)
    i += 1

1
2
3
4
5


### 1.2.2 `for` loop

Python's for statement iterates over the items of any sequence (a list or a string), in the order that they appear in the sequence.

Here's the syntax for the `for` statement:

```python
for target in iterable:
    statement(s)
```

In [18]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)

apple
banana
cherry


In [19]:
for x in "banana":
    print(x)

b
a
n
a
n
a


### 1.2.3 `break`

With the `break` statement we can stop the loop before it has looped through all the items.

In [22]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)
    if x == "banana":
        break

apple
banana


In [1]:
i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i += 1

1
2
3


### 1.2.3 `continue`

With the `continue` statement we can stop the current iteration of the loop, and continue with the next.

In [23]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        continue
    print(x)

apple
cherry


In [2]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)

1
2
4
5
6


### 1.2.4 Loops with an `else` Block

The `else` block after a loop block (`for` or `while`) will **only be executed when the loop ends naturally without meeting a `break` statement**. 

In other words, if a `for` loop has iterate all elements inside an iterable or the condition in `while` loop becomes true, but no `break` statement has been triggered in the loop process, then the `else` block will be executed. 

Below is a specific code explanation for this loop-else syntax. 

In [24]:
sum = 0
for i in range(6):
    sum += i
else:
    print("This loop ends naturaly.")
print(sum)

This loop ends naturaly.


In [27]:
sum = 0
for i in range(6):
    sum += i
    if i>4:
        break
else:
    print("This loop ends naturaly.")
print(sum)

15


Here we use this syntax in the scenario of searching primes.

In [29]:
# find all primes up to a specific positive integer
def primes_up_to_n(n):
    primes = []
    for x in range(2,n+1):
        for p in primes:
            if x % p == 0:
                break
        else:
            primes.append(x)
    return primes

print(primes_up_to_n(50))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


# 3. Some Other Things

## 3.1 `pass` Statement

We use a `pass` statement when a statement is required syntactically but we don't want to take any actions here or we haven't decided what to do here.

A `pass` statement could be considered as a placeholder that doesn't do anything.

In [9]:
x = 5
if x > 3:
                # a statement is required here syntactically

SyntaxError: unexpected EOF while parsing (<ipython-input-9-287ecce6bcef>, line 3)

In [ ]:
# allow you to keep thinking at a more abstract level.
def initlog(*args):
    pass   # Remember to implement this!

```python
if condition1(x):
    process1(x)
elif condition2(x):
    pass          # nothing to be done in this case
elif condition3(x):
    process3(x)
else:
    process_default(x)
```

## 3.2 `list` Compression 

This is a very **efficient and elegant** way to create a list. A frequently used mechanism in Python. You'll like it.

It is a consise way to avoid using a `for` or `while` block for list creating. 

Its syntax is as followed, **working as an expression, and with a result as a list**. 

```python
[expression for item in iterable + more for/if clauses]
```

- `expression` is commonly an expression related to the current `item`
- after `for item in iterablethe`, you can add zero or more `for` or `if` clauses

### Only one `for` clause

In below example, two ways to make each element inside a sequence squared are provided. 

In [12]:
r = range(5)

# the first way, using for loop
result1 = []
for x in r:
    result1.append(x**2)
    
# the second way, by list compression
result2 = [x**2 for x in r]

print(result1)
print(result2)

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]


The expression is not required to be related the current item.

Here I want to creat a list with a given value repeated specific times.

In [14]:
n = 10
value = 3

# the first way, using for loop
result1 = []
for x in range(n):
    result1.append(value)
    
# the second way, by list compression
result2 = [value for x in range(n)]

print(result1)
print(result2)

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


### With more `for`/`if` clauses

Find the digits inside a string.

In [15]:
string = "34 Hello 84345 World"

# list compression
numbers = [x for x in string if x.isdigit()]
print(numbers)

# the equivalent for/if blocks
numbers = []
for x in string:
    if x.isdigit():
        numbers.append(x)
print(numbers)

['3', '4', '8', '4', '3', '4', '5']
['3', '4', '8', '4', '3', '4', '5']


Find multiples for both 2 and 5.

In [22]:
r = range(100)

print([y for y in r if y % 2 == 0 if y % 5 == 0])

# the equivalent nested if blocks
result = []
for y in r:
    if y%2==0:
        if y%5==0:
            result.append(y)
print(result)

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


Combine the elements inside two lists if they are not equal.

In [18]:
vec1 = [1, 2, 3]
vec2 = [3, 4, 5]

# list compression
print([(x, y) for x in vec1 for y in vec2 if x != y])

# the equivalent for/if blocks
result = []
for x in vec1:
    for y in vec2:
        if x!=y:
            result.append((x, y))
print(result)

[(1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5)]
[(1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5)]


Flatten a nested list.

In [20]:
vec = [[1,2,3], [4,5,6], [7,8,9]]

# list compression
print([y for x in vec for y in x])

# the equivalent nested for blocks
result = []
for x in vec:
    for y in x:
        result.append(y)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


### More kinds of `expression`s

Use short hand `if`-`else` or conditional expression as `expression`.

In [30]:
import random

nums = [random.randint(0,100) for i in range(10)]
print(nums)

# list compression
print(["Even" if n%2==0 else "Odd" for n in nums])

# the equivalent for/if blocks
result = []
for n in nums:
    if n % 2 == 0:
        result.append("Even")
    else:
        result.append("Odd")
print(result)

[70, 31, 25, 63, 60, 50, 82, 43, 93, 73]
['Even', 'Odd', 'Odd', 'Odd', 'Even', 'Even', 'Even', 'Odd', 'Odd', 'Odd']
['Even', 'Odd', 'Odd', 'Odd', 'Even', 'Even', 'Even', 'Odd', 'Odd', 'Odd']


Nested list compression. That is, use list compression as the expression in list compression.

I want to transpose a matrix in this example.

In [39]:
matrix = [
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12],
]
print(matrix)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [40]:
import numpy as np
matrix_np = np.array(matrix)
print("Before transpose:\n", matrix_np)
print("After transpose:\n", matrix_np.transpose())

Before transpose:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
After transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [42]:
# list compression
for vec in [[row[i] for row in matrix] for i in range(len(matrix[0]))]:
     print(vec)

# the equivalent for blocks
result = []
for i in range(len(matrix[0])):
    sub = []
    for row in matrix:
        sub.append(row[i])
    result.append(sub)
for vec in result:
    print(vec)

[1, 5, 9]
[2, 6, 10]
[3, 7, 11]
[4, 8, 12]
[1, 5, 9]
[2, 6, 10]
[3, 7, 11]
[4, 8, 12]


### Key points on list compression

- It is an elegant way to define and create lists.
- It is generally more compact and faster than normal functions or loops for creating list.
- However, we should avoid writing very long or complicated list comprehensions which are not user-friendly.
- Every list comprehension has an equivalent for loop block, but not not vice versa.